pbs_passthrough/app.py
from flask import Flask
from routes import home, about, passthrough, demo, facial_recognition, query

app = Flask(__name__)

# Registering blueprints for routes
app.register_blueprint(home.bp)
app.register_blueprint(about.bp)
app.register_blueprint(passthrough.bp)
app.register_blueprint(demo.bp)
app.register_blueprint(facial_recognition.bp)
app.register_blueprint(query.bp)

if __name__ == "__main__":
    app.run(debug=True)

pbs_passthrough/routes/about.py
from flask import Blueprint, render_template

bp = Blueprint("about", __name__)

@bp.route("/about")
def about():
    return render_template("about.html")

pbs_passthrough/routes/demo.py
from flask import Blueprint, render_template, send_file
import os 
import boto3
from dotenv import load_dotenv

# regiseter with blueprint
bp = Blueprint("demo", __name__)

# load dotenv
load_dotenv()

# instnatiate s3 client 
s3 = boto3.client("s3", 
                  region_name="us-east-1", 
                  aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"), 
                  aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"))

# set bucket
S3_BUCKET = "pbs-passthrough"

@bp.route("/demo")
def demo():
    response = s3.get_object(Bucket=S3_BUCKET, Key="grantchester_sample.mp4")
    return send_file(response["Body"], mimetype="video/mp4")

pbs_passthrough/routes/facial_recognition.py
from flask import Blueprint, request, jsonify
import os
import base64
from static.helpers import FacialRecognition, convert_image_to_bytea

bp = Blueprint("facial-recognition", __name__)

facial_recognition = FacialRecognition()

@bp.route("/facial-recognition", methods=["POST"])
def perform_facial_regonition():
    if "image" not in request.files:
        return jsonify({"error": "No image file in request"}), 400
    
    image_file = request.files["image"]
    image_path = os.path.join("/tmp", "temp_image.jpg")
    image_file.save(image_path)

    # run facial recognition pipeline
    boxed_image, scores, embeddings = facial_recognition.embedding_pipeline(image_path)

    # create list of embedding strings 
    embedding_strings = []
    for embedding in embeddings:
        embedding_string = ", ".join(map(str, embedding))
        embedding_strings.append(embedding_string)

    # encode image 
    image_bytes = convert_image_to_bytea(boxed_image)
    encoded_boxed_image = base64.b64encode(image_bytes).decode('utf-8')

    results = {
        "boxed_image": encoded_boxed_image,
        "embeddings": embedding_strings
    }

    os.remove(image_path)

    return jsonify(results)

pbs_passthrough/routes/home.py
from flask import Blueprint, render_template

bp = Blueprint("home", __name__)

@bp.route("/")
def home():
    return render_template("home.html")

pbs_passthrough/routes/passthrough.py
from flask import Blueprint, render_template

bp = Blueprint("passthrough", __name__)

@bp.route("/passthrough")
def passthrough():
    return render_template("passthrough.html")

pbs_passthrough/routes/query.py
from flask import Blueprint, request, jsonify
import psycopg2
import os 
from dotenv import load_dotenv

bp = Blueprint("query", __name__)

load_dotenv()

@bp.route("/query", methods=["POST"])
def query_db():

    # get embeddings from the request
    embeddings = request.json.get("embeddings", [])

    # instantaite a dictionary to hold our results
    all_results = {}

    # iterate over available facial embeddings
    for idx, embedding in enumerate(embeddings):
        
        # connect to db and create cursor
        conn = psycopg2.connect(
            host=os.getenv("PG_HOST"),
            database=os.getenv("PG_DB"),
            user=os.getenv("PG_USER"),
            password=os.getenv("PG_PASSWORD"),
            port="5432"
        )
        cur = conn.cursor()

        # define and execute query
        similarity_query = f"SELECT id, actor_actress, about, 1-(facial_embedding <=>'[{embedding}]') AS score FROM masterpiece_grantchester ORDER BY facial_embedding <=> '[{embedding}]' LIMIT 3;"
        cur.execute(similarity_query)

        # get results
        rows = cur.fetchall()

        # format results
        results = [{"id": row[0], "actor_actress": row[1], "about": row[2], "similarity_score": row[3]} for row in rows]

        # close connection
        cur.close()
        conn.close()

        # append to dictionary, keeping track of face number
        all_results[f"face_{idx}"] = results

    return jsonify(all_results)

pbs_passthrough/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about_styles.css') }}">
</head>
<body>
    <nav class="nav-links">
        <ul>
            <li><a href="/">/</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a href="/passthrough">DEMO</a></li>
        </ul>
    </nav>
    <main class="about-content">
        <header class="page-title">
            <h1>a new way to watch.</h1>
            <h3>powered by facial recognition</h3>
            <section class="tag-container">
                <span class="tag">computer vision</span>
                <span class="tag">vector databases</span>
            </section>
        </header>
        <div class="content-box">
            <div class="article-container">
                <div class="image-container">
                    <img src="../static/images/xray_example.png" alt="image">
                </div>
                <div class="paragraph-container">
                    <p>
                        powered by facial recognition, passthrough facilitates the retrieval and service or person-specific
                        metadata within your video content. 
        
                        passthrough can help viewers enjoy an enhanced viewing experience by providing them with actor/actress names, 
                        bios, trivia, and more! 
        
                        inspired by Prime Video's X-Ray service, passthrough aims to provide comparable data using open source technologies.
                    </p>
                </div>
            </div>
            <div class="article-container">
                <div class="paragraph-container">
                    <p>
                        at a specified frame rate, passthrough extracts frames and uses a 
                        multi-task cascaded convolutional neural network (MTCCN) to search for faces. 
                        
                        in the provided image, two faces were detected by the MTCNN model, each accompanied by bounding box 
                        coordinates and a confidence score.

                        identified faces are embedded using FaceNet and will eventually be used as query 
                        parameters.
                        
                    </p>
                </div>
                <div class="image-container">
                    <img src="../static/images/annotated_image.png" alt="image">
                </div>
            </div>
            <div class="article-container">
                <div class="image-container">
                    <!-- <img src="../static/images/query_example.png" alt="image"> -->
                    <img src="../static/images/json_response.png" alt="image">
                </div>
                <div class="paragraph-container">
                    <p>
                        for each embedded face, a query is sent to a database of known faces. 
                        
                        the query compares the provided embeddings with its stored facial embeddings using the 
                        cosine similarity metric and returns the top 3 results along with any associated metadata.

                        passthrough's vector search is suppored by PostgreSQL's pgvector extension.                     
                    </p>
                </div>
            </div>
        </div>
    </main>
    <script src="{{ url_for('static', filename='js/track_active_link.js') }}"></script>
</body>
</html>

pbs_passthrough/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home_style.css') }}">
</head>
<body>
    <nav class="nav-links">
        <ul>
            <li><a href="/">/</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a href="/passthrough">DEMO</a></li>
        </ul>
    </nav>
    <main class="home-content">
        <header class="main-title">
            <h1>passthrough.</h1>
            <hr>
            <h2>a new way to watch</h2>
        </header>
        <section class="description">
            <span class="tag">hack-day</span>
            <span class="tag">spring-2024</span>
        </section>
    </main>
    <script src="{{ url_for('static', filename='js/track_active_link.js') }}"></script>
</body>
</html>

pbs_passthrough/templates/passthrough.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/passthrough_styles.css') }}">
</head>
<body>
    <nav class="nav-links">
        <ul>
            <li><a href="/">/</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a href="/passthrough">DEMO</a></li>
        </ul>
    </nav>
    <main class="page-content">
        <header class="page-title">
            <h1>passthrough at work.</h1>
            <h3>grantchester</h3>
            <section class="tag-container">
                <span class="tag">season 1</span>
                <span class="tag">masterpiece mysteries</span>
            </section>
        </header>
        <section class="passthrough-content">
            <div class="video-image-container">
                <video id="videoPlayer" controls>
                    <source src="{{ url_for('demo.demo') }}" type="video/mp4">
                </video>
                <div class="canvas-container">
                    <canvas id="frameCapture"> </canvas>
                </div>
            </div>
            <div class="code-container">
                <pre><code id="queryResult">Query results pending ... </code></pre>
            </div>
        </section>
    </main>
    <p id="frameNumber">frame number: </p>
    <script src="{{ url_for('static', filename='js/process_video.js') }}"></script>
    <script src="{{ url_for('static', filename='js/track_active_link.js') }}"></script>
</body>
</html>